package consts

const (
	ReplacePrefix = "value@"
	ReplaceSuffix = "@"
)

// symbol
const (
	Empty        = ""
	Blank        = " "
	LeftBracket  = "("
	RightBracket = ")"
	Comma        = ","
	Semicolon    = ";"
	NextLine     = "\n"
	EQ           = "="
	NE           = "!="
	LT           = "<"
	GT           = ">"
	LE           = "<="
	GE           = ">="
)

// keyword
const (
	SELECT    = "select"
	UPDATE    = "update"
	DELETE    = "delete"
	INSERT    = "insert"
	INTO      = "into"
	Value     = "value"
	Values    = "values"
	FROM      = "from"
	WHERE     = "where"
	SET       = "set"
	LEFT      = "left"
	RIGHT     = "right"
	INNER     = "inner"
	OUTER     = "outer"
	JOIN      = "join"
	GROUP     = "group"
	GroupBy   = "group by"
	ORDER     = "order"
	OrderBy   = "order by"
	HAVING    = "having"
	LIMIT     = "limit"
	OFFSET    = "offset"
	AS        = "as"
	AND       = "and"
	ON        = "on"
	OR        = "or"
	IN        = "in"
	NotIn     = "not in"
	IS        = "is"
	IsNot     = "is not"
	NOT       = "not"
	LIKE      = "like"
	By        = "by"
	DISTINCT  = "distinct"
	OVER      = "over"
	PARTITION = "partition"
	CASE      = "case"
	WHEN      = "when"
	THEN      = "then"
	END       = "end"
	ASC       = "asc"
	DESC      = "desc"
)
